### ISSUE TITLE
load_data.py issue on Windows machine

### ISSUE THREAD

**Issue by petepall** [talkpython/data-driven-web-apps-with-pyramid-and-sqlalchemy#3]
When trying to execute the load_data script on a windows machine, one gets a deprecation warning on the usage of macpath as well as an AttributeError on the progressbar elment.

c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py:7: DeprecationWarning: the macpath module is deprecated in 3.7 and will be removed in 3.8
  from macpath import split

Connecting to DB at: sqlite:///c:\python programs\data-driven-web-apps\ch10-using-sqlalchemy\pypi_using_sqlalchemy\pypi\db\pypi.sqlite
Loading files from c:\Python programs\data-driven-web-apps\pypi-top-100
Found 96 files, loading ...
Traceback (most recent call last):
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 397, in <module>
    main()
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 30, in main
    file_data = do_load_files()
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 175, in do_load_files
    maxval=len(files)) as bar:
AttributeError: `__enter__
`

In the coding listed on GitHub, the item is coded as with progressbar.ProgressBar(max_value=len(files)) as bar:

When using this code one get's a TypeError.

Traceback (most recent call last):
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 397, in <module>
    main()
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 30, in main
    file_data = do_load_files()
  File "c:/Python programs/data-driven-web-apps/Ch10-Using-sqlalchemy/pypi_using_sqlalchemy/pypi/bin/load_data.py", line 175, in do_load_files
    max_value=len(files)) as bar:
TypeError: `__init__()` got an unexpected keyword argument 'max_value'

upon changing the keyword argument to maxval which I could find in the signature of the constructor for the class I get the attribute error,

```
def __init__(self, maxval=None, widgets=None, term_width=None, poll=1,
                 left_justify=True, fd=None):
```

**Comment by petepall** [comment]
FYI: I commented the progressbar code from the script in order to load the data and continue the course

**Comment by mikeckennedy** [comment]
Hi @petepall 

I'm not sure what issue you're hitting but this code does work on Windows (10 anyway). See the screenshot below.

I am guessing maybe one of the dependent libraries didn't get installed correctly? Or it was installed into a virtual environment but it wasn't activated. Something like that.

Best,
Michael

<img width="1264" alt="screen shot 2018-08-25 at 7 13 09 am" src="https://user-images.githubusercontent.com/2035561/44619130-82258f00-a836-11e8-9250-2bbf6696d38b.png">

**Comment by mikeckennedy** [comment]
Also, notice no warnings on macpath or anything else in my output. I'm using Python 3.7 from python.org.

**Comment by saryeHaddadi** [comment]
Hi @petepall, I got the same issue.
The reason was that you installed the package `progressbar `instead of `progressbar2`.
```
pip uninstall progressbar 
pip install progressbar2
```

**Comment by mikeckennedy** [comment]
Nice catch, thanks @saryeHaddadi Yes, this requires `progressbar2`.
