### ISSUE TITLE
Problem while trying to create a sqlite database

### ISSUE THREAD

**Issue by greener2015** [talkpython/data-driven-web-apps-with-pyramid-and-sqlalchemy#6]
Michael, 
I am working through 'Modeling data with SQLAlchemy classes'. 
I have completed the entire chapter however, the final code produces an error. 
Any suggestion, what could cause a problem ?
Thanks, 
Chris

`/Users/chris/Dev/Python/alchemy/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/pycharm_load_entry_point.py /Users/chris/Dev/Python/alchemy/development.ini
Connecting to DB at: sqlite:////Users/chris/Dev/Python/alchemy/alchemy/db/alchemy.sqlite
Traceback (most recent call last):
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/pycharm_load_entry_point.py", line 12, in <module>
    sys.exit(f())
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/chris/Dev/Python/alchemy/alchemy/__init__.py", line 13, in main
    init_db(config)
  File "/Users/chris/Dev/Python/alchemy/alchemy/__init__.py", line 71, in init_db
    DbSession.global_init(db_file)
  File "/Users/chris/Dev/Python/alchemy/alchemy/data/db_session.py", line 28, in global_init
    SqlAlchemyBase.metadata.create_all(engine)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/chris/Dev/Python/alchemy/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)

Process finished with exit code 1
`

**Comment by mikeckennedy** [comment]
Hi @greener2015 

The error is `OperationalError: unable to open database file`. Can you verify the directory exists? Just open a terminal and try `cd /Users/chris/Dev/Python/alchemy/alchemy/db/` and see what happens. I guess there could be a permission issue there as well.

**Comment by greener2015** [comment]
I had to reinstall my system. I will report back when I import my project back.

**Comment by mikeckennedy** [comment]
Great, thanks.
